# This is a basic workflow to help you get started with Actions

name: msm-Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [beryllium_clear_2301]
  pull_request:
    branches: [beryllium_clear_2301]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Image Build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 8
      matrix:
        device:
          # sm8150
          #- mh2lm
          #- betalm
          #- nabu
          #- vayu
          #- cepheus
          #- hotdog
          #- guacamole
          
          # sdm845
          #- polaris
          #- perseus
          - beryllium-ebbg
          - beryllium-tianma
          
          # sm7325
          #- mona
          #- lisa
          
          # msm8998
          #- cheeseburger

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install required packages
        run: |
          sudo dpkg --add-architecture i386 
          wget -qO - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
          sudo apt-add-repository "deb https://dl.winehq.org/wine-builds/ubuntu $(lsb_release -cs) main"
          sudo apt-get update
          sudo apt-get -y install build-essential uuid-dev clang llvm iasl nasm gcc-aarch64-linux-gnu abootimg python3-distutils python3-pil python3-git gettext
          sudo apt-get install --install-recommends winehq-stable libgcc-s1:i386 libstdc++6:i386

      - name: Build an image for ${{ matrix.device }}
        run: |
          ./build.sh --device ${{ matrix.device }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with: # Artifact name
          name: ${{ matrix.device }}
          # A file, directory or wildcard pattern that describes what to upload
          path: ./*.img
